[default]
    locale = "en-us"

    [default.extend-words]
        criticals = "criticals"

[files]
    extend-exclude = [
        "*_cache",
        ".env.secrets",
        ".venv",
        "CHANGELOG.md",
        "fixtures",
        "scripts/install_certifi.py",
        "static",
    ]
