---
coverage:
  status:
    patch:
      default:
        target: 75%
        threshold: 0%
        informational: true
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
